// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend_agua.Infraestructure.Database;

#nullable disable

namespace backend_agua.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260319192859_AddLideresOptionalToComunaYComunidad")]
    partial class AddLideresOptionalToComunaYComunidad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend_agua.Models.Comuna", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LiderCedula")
                        .HasColumnType("text");

                    b.Property<string>("LiderNombre")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ParroquiaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParroquiaId");

                    b.ToTable("Comunas");
                });

            modelBuilder.Entity("backend_agua.Models.Comunidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComunaId")
                        .HasColumnType("uuid");

                    b.Property<string>("LiderCedula")
                        .HasColumnType("text");

                    b.Property<string>("LiderNombre")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ComunaId");

                    b.ToTable("Comunidades");
                });

            modelBuilder.Entity("backend_agua.Models.Municipio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Municipios");
                });

            modelBuilder.Entity("backend_agua.Models.Parroquia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MunicipioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MunicipioId");

                    b.ToTable("Parroquias");
                });

            modelBuilder.Entity("backend_agua.Models.PersonaAfectada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Condicion")
                        .HasColumnType("integer");

                    b.Property<int>("Edad")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReporteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReporteId");

                    b.ToTable("PersonasAfectadas");
                });

            modelBuilder.Entity("backend_agua.Models.Reporte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ApoyoAdicionalLitros")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadCasosDiarrea")
                        .HasColumnType("integer");

                    b.Property<int?>("Caudal")
                        .HasColumnType("integer");

                    b.Property<string>("ChoferCedula")
                        .HasColumnType("text");

                    b.Property<string>("ChoferNombreApellido")
                        .HasColumnType("text");

                    b.Property<Guid>("ComunidadId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConflictosExplicacion")
                        .HasColumnType("text");

                    b.Property<string>("DetalleAlcaldia")
                        .HasColumnType("text");

                    b.Property<string>("DetalleGobernacion")
                        .HasColumnType("text");

                    b.Property<string>("DetalleInstitucionNacional")
                        .HasColumnType("text");

                    b.Property<int>("Estatus")
                        .HasColumnType("integer");

                    b.Property<int>("FamiliasBeneficiadas")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FugaLugar")
                        .HasColumnType("text");

                    b.Property<int?>("FugaTipo")
                        .HasColumnType("integer");

                    b.Property<int?>("HorasSuministro")
                        .HasColumnType("integer");

                    b.Property<int?>("LitrosCisterna")
                        .HasColumnType("integer");

                    b.Property<bool>("LlegaPorTuberia")
                        .HasColumnType("boolean");

                    b.Property<int?>("Partido")
                        .HasColumnType("integer");

                    b.Property<bool>("RecibeCisterna")
                        .HasColumnType("boolean");

                    b.Property<bool>("TieneAlcaldia")
                        .HasColumnType("boolean");

                    b.Property<bool>("TieneConflictos")
                        .HasColumnType("boolean");

                    b.Property<bool>("TieneDiarrea")
                        .HasColumnType("boolean");

                    b.Property<bool>("TieneDolorAbdominal")
                        .HasColumnType("boolean");

                    b.Property<bool>("TieneFugas")
                        .HasColumnType("boolean");

                    b.Property<bool>("TieneGobernacion")
                        .HasColumnType("boolean");

                    b.Property<bool>("TieneInstitucionNacional")
                        .HasColumnType("boolean");

                    b.Property<bool>("TienePartido")
                        .HasColumnType("boolean");

                    b.Property<bool>("TieneTanque")
                        .HasColumnType("boolean");

                    b.Property<bool>("TieneTrancas")
                        .HasColumnType("boolean");

                    b.Property<bool>("TieneVentaIlegal")
                        .HasColumnType("boolean");

                    b.Property<bool>("TieneVomitos")
                        .HasColumnType("boolean");

                    b.Property<int?>("TipoCisterna")
                        .HasColumnType("integer");

                    b.Property<int?>("TipoTanque")
                        .HasColumnType("integer");

                    b.Property<string>("TrancaDuracion")
                        .HasColumnType("text");

                    b.Property<string>("TrancaLugar")
                        .HasColumnType("text");

                    b.Property<string>("TrancaPropiciaNombre")
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("VehiculoColor")
                        .HasColumnType("text");

                    b.Property<string>("VehiculoMarcaModelo")
                        .HasColumnType("text");

                    b.Property<string>("VehiculoPlaca")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ComunidadId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("backend_agua.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ComunidadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ComunidadId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("backend_agua.Models.Comuna", b =>
                {
                    b.HasOne("backend_agua.Models.Parroquia", "Parroquia")
                        .WithMany("Comunas")
                        .HasForeignKey("ParroquiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parroquia");
                });

            modelBuilder.Entity("backend_agua.Models.Comunidad", b =>
                {
                    b.HasOne("backend_agua.Models.Comuna", "Comuna")
                        .WithMany("Comunidades")
                        .HasForeignKey("ComunaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comuna");
                });

            modelBuilder.Entity("backend_agua.Models.Parroquia", b =>
                {
                    b.HasOne("backend_agua.Models.Municipio", "Municipio")
                        .WithMany("Parroquias")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("backend_agua.Models.PersonaAfectada", b =>
                {
                    b.HasOne("backend_agua.Models.Reporte", "Reporte")
                        .WithMany("PersonasAfectadas")
                        .HasForeignKey("ReporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reporte");
                });

            modelBuilder.Entity("backend_agua.Models.Reporte", b =>
                {
                    b.HasOne("backend_agua.Models.Comunidad", "Comunidad")
                        .WithMany()
                        .HasForeignKey("ComunidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend_agua.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comunidad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend_agua.Models.Usuario", b =>
                {
                    b.HasOne("backend_agua.Models.Comunidad", "Comunidad")
                        .WithMany("Usuarios")
                        .HasForeignKey("ComunidadId");

                    b.Navigation("Comunidad");
                });

            modelBuilder.Entity("backend_agua.Models.Comuna", b =>
                {
                    b.Navigation("Comunidades");
                });

            modelBuilder.Entity("backend_agua.Models.Comunidad", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("backend_agua.Models.Municipio", b =>
                {
                    b.Navigation("Parroquias");
                });

            modelBuilder.Entity("backend_agua.Models.Parroquia", b =>
                {
                    b.Navigation("Comunas");
                });

            modelBuilder.Entity("backend_agua.Models.Reporte", b =>
                {
                    b.Navigation("PersonasAfectadas");
                });
#pragma warning restore 612, 618
        }
    }
}
